POST http://localhost:3000/api/scenes HTTP/1.1
Content-Type: application/json

{
  "nextId": 2,
  "choiceId": 3,
  "prevId": 1,
  "talkingChar": "Vita",
  "text": "Test",
  "scenePicsId": 3
}

###################

POST http://localhost:3000/api/games HTTP/1.1
Content-Type: application/json

{
  "gameName": "VisualNovel",
  "scenes": [],
  "infoId": 2
}