POST http://localhost:3000/api/scenes HTTP/1.1
Content-Type: application/json

{
  "nextId1": 2,
  "nextId2": 3,
  "prevId": 1,
  "talkingChar": "Vita",
  "text": "Test",
  "scenePicsId": 3,
  "picLeft": 1,
  "picRight": 2,
  "picBackground": 3,
  "gameId": 1
}

###################

POST http://localhost:3000/api/games HTTP/1.1
Content-Type: application/json

{
  "name": "VisualNovel",
  "creator": "HttpCreator",
  "description": "http description text"
}

########################

POST http://localhost:3000/api/games HTTP/1.1
Content-Type: application/json

{
  "name": "VisualNovel",
  "description": "http description text"
}

#########################

POST http://localhost:3000/api/pics HTTP/1.1
Content-Type: application/json

{
  "picId" : 2,
  "url": "../img/Characters/monster.png",
  "picName": "monster",
  "gameId": 2
}

#############

GET http://localhost:3000/api/pics/vita HTTP/1.1